# Generated by Django 4.2.3 on 2023-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=13)),
                ('kurs', models.IntegerField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
